[versions]
junit-jupiter = "5.12.1"
asm = "9.7"
stianloader = "0.1.0-a20240426"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
stianloader-remapper = { module = "org.stianloader:stianloader-remapper", version.ref = "stianloader" }

[bundles]
asm = ["asm", "asm-analysis", "asm-commons", "asm-tree", "asm-util"]